In [46]:
#Necessary imports
import torch
import torch.nn as nn

In [47]:
#Initializing linear regressor model
torch.manual_seed(1)
model = nn.Linear(in_features=1, out_features=1)

In [48]:
print (model.bias)
print (model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True)
Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [49]:
x = torch.tensor([[2.0], [3.0]])    #tensor should be float
model(x)

tensor([[0.5891],
        [1.1044]], grad_fn=<AddmmBackward>)

In [56]:
class LR(nn.Module):
    def __init__(self, in_size, out_size):
        super().__init__()
        self.linear = nn.Linear(in_size, out_size)
    def forward(self, x):
        return self.linear(x)

In [57]:
model = LR(1, 1)
x = torch.tensor([[2.0], [3.0]])
model.forward(x)

tensor([[0.1556],
        [0.2946]], grad_fn=<AddmmBackward>)